apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: thorabh/django-test:3
        ports:
        - containerPort: 8000
        env:
        - name: DB_PASSWORD
          value: "thorabh"
        - name: DB_HOST
          value: "postgres-db-service"
      
        # Add other environment variables as needed

---
apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
